version: "3.1"

services:
  traefik:
    image: traefik:1.6
    restart: always
    hostname: traefik
    container_name: traefik
    depends_on: 
      - jenkins
      - sonarqube
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "${WORKDIR-.}/acme.json:/acme.json"
      - "${WORKDIR-.}/traefik.toml:/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock"

  postgres:
    image: postgres:10.3
    container_name: postgres
    environment:
      POSTGRES_USER: ${SONARQUBE_JDBC_USER:-sonar} 
      POSTGRES_PASSWORD: ${SONARQUBE_JDBC_PASSWORD:-sonar} 
    volumes:
      - postgres_data:/var/lib/postgresql/data

  jenkins:
    image: alapshin/jenkins-master:2.107.2-3
    restart: always
    container_name: jenkins
    hostname: jenkins
    environment:
      DOCKER_GROUP: docker
      DOCKER_SOCKET: /var/run/docker.sock
      JENKINS_HOST:
      JENKINS_USER: jenkins
      JENKINS_URL: "https://${JENKINS_HOST}"
      SONARQUBE_URL: "https://${SONARQUBE_HOST}"
      CASC_JENKINS_CONFIG: /var/jenkins_home/jenkins.yml
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.backend=jenkins"
      - "traefik.frontend.rule=Host:${JENKINS_HOST-localhost}"
    secrets:
      - source: admin_password
        target: ADMIN_PASSWORD

      - source: slack_token
        target: SLACK_TOKEN

      - source: github_token
        target: GITHUB_TOKEN

      - source: github_username
        target: GITHUB_USERNAME

      - source: github_password
        target: GITHUB_PASSWORD

      - source: sonarqube_token
        target: SONARQUBE_TOKEN
    volumes:
      - "jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${WORKDIR-.}/jenkins.yml:/var/jenkins_home/jenkins.yml"

  sonarqube:
    image: alapshin/sonarqube:6.7.3
    container_name: sonarqube
    depends_on: 
      - postgres
    expose:
      - "9000"
    environment:
      SONARQUBE_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
      SONARQUBE_JDBC_USERNAME: ${SONARQUBE_JDBC_USER:-sonar}
      SONARQUBE_JDBC_PASSWORD: ${SONARQUBE_JDBC_PASSWORD:-sonar}
    labels:
      - "traefik.enable=true"
      - "traefik.port=9000"
      - "traefik.backend=sonarqube"
      - "traefik.frontend.rule=Host:${SONARQUBE_HOST-localhost}"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled_plugins:/opt/sonarqube/lib/bundled-plugins

volumes:
  jenkins_home:
  postgres_data:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled_plugins:

secrets:
  admin_password:
    file: "${WORKDIR-.}/secrets/admin_password"
  slack_token:
    file: "${WORKDIR-.}/secrets/slack_token"
  github_token:
    file: "${WORKDIR-.}/secrets/github_token"
  github_username:
    file: "${WORKDIR-.}/secrets/github_username"
  github_password:
    file: "${WORKDIR-.}/secrets/github_password"
  sonarqube_token:
    file: "${WORKDIR-.}/secrets/sonarqube_token"
