version: "3.1"

services:
  traefik:
    ports:
      - "8080:8080"
    volumes:
      - "${WORKDIR-.}/traefik.dev.toml:/traefik.toml"

  jenkins:
    volumes:
      - ./master/init.groovy.d:/var/jenkins_home/init.groovy.d
